@baseUrl = http://localhost:3333

# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "product_id": "66d9d2f38c9cd8839bc649f7",
  "quantity": 1,
  "address": "Rua dos Sonhos",
  "payment_method": "CREDIT_CARD"
}